# Site
title: "Kevin Oliveira"
baseurl: ""
url: "https://kevinoliveira.com.br"
permalink: /:collection/:title/

collections:
  portfolio:
    output: true

# Build
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/_scss
  style: compressed
    
exclude:
  - Gemfile
  - node_modules
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE
