# Site
title: "Kevin Oliveira"
description: "Front-end at Din Digital, previously Agência Murilhas. Catholic, musician and designer."
baseurl: ""
url: "https://kevinoliveira.com.br"
permalink: /:title/

# Build
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/_scss
  style: compressed
    
exclude:
  - Gemfile
  - node_modules
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE
